version: "2"
services:
  mariadb:
    image: "bitnami/mariadb:10.3"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
    links:
      - mariadb
    ports:
      - 9000:80
    volumes:
      - /sessions

  myapp:
    tty: true # Enables debugging capabilities when attached to this container.
    image: bitnami/rails:6
    environment:
      - DATABASE_HOST=mariadb
      - DATABASE_NAME=my_app_development
      - RAILS_ENV=development
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./app:/app

